### ISSUE TITLE
high ascii chars

### ISSUE THREAD

**Issue by iandoug** [Pomax/PHP-Font-Parser#12]
hi

Re your sample code which looks for letter "g" ... what if I needed to check for a glyph much higher up, eg U+232B for example?

Thanks, Ian

**Comment by Pomax** [comment]
a technical comment: there is no "high ascii", ASCII is a 7-bit encoding scheme, specific to US and US-international computers. It's one of *many* encodings that a font can support, and this parser ignores all of them: it only properly parses fonts that use the Unicode scheme (which is *almost* identical to ASCII for the first 127 code points) with CMAP format 4 and 12 (effectively, UCS-2 and UCS-4).

So to answer the actual question: if you need a unicode glyph, that works fine. I've used it to extract glyphs from the CJK Ideograph blocks A and B without any problems.
